# Dictionary để reverse các giá trị từ label sang index
reverse_mapping = {
    # Workclass
    "Private": "Private",
    "Local Government": "Local-gov",
    "Self-Employed (Not Incorporated)": "Self-emp-not-inc",
    "Federal Government": "Federal-gov",
    "State Government": "State-gov",
    "Self-Employed (Incorporated)": "Self-emp-inc",
    "Without Pay": "Without-pay",

    # Marital-status
    "Never Married": "Never-married",
    "Married (Civilian Spouse)": "Married-civ-spouse",
    "Widowed": "Widowed",
    "Separated": "Separated",
    "Divorced": "Divorced",
    "Married (Spouse Absent)": "Married-spouse-absent",
    "Married (Armed Forces Spouse)": "Married-AF-spouse",

    # Occupation
    "Machine Operator / Inspector": "Machine-op-inspct",
    "Farming / Fishing": "Farming-fishing",
    "Protective Services": "Protective-serv",
    "Other Service": "Other-service",
    "Professional / Specialty": "Prof-specialty",
    "Craft / Repair": "Craft-repair",
    "Admin / Clerical": "Adm-clerical",
    "Executive / Managerial": "Exec-managerial",
    "Technical Support": "Tech-support",
    "Sales": "Sales",
    "Private House Service": "Priv-house-serv",
    "Transport / Moving": "Transport-moving",
    "Handlers / Cleaners": "Handlers-cleaners",
    "Armed Forces": "Armed-Forces",

    # Relationship
    "Own Child": "Own-child",
    "Husband": "Husband",
    "Not in Family": "Not-in-family",
    "Unmarried": "Unmarried",
    "Wife": "Wife",
    "Other Relative": "Other-relative",

    # Race
    "Black / African American": "Black",
    "White": "White",
    "Other": "Other",
    "American Indian / Eskimo": "Amer-Indian-Eskimo",
    "Asian / Pacific Islander": "Asian-Pac-Islander",

    # Gender
    "Male": "Male",
    "Female": "Female",

    # Native-country
    "United States": "United-States",
    "Peru": "Peru",
    "Guatemala": "Guatemala",
    "Mexico": "Mexico",
    "Dominican Republic": "Dominican-Republic",
    "Ireland": "Ireland",
    "Germany": "Germany",
    "Philippines": "Philippines",
    "Thailand": "Thailand",
    "Haiti": "Haiti",
    "El Salvador": "El-Salvador",
    "Puerto Rico": "Puerto-Rico",
    "Vietnam": "Vietnam",
    "South Korea": "South",
    "Colombia": "Columbia",
    "Japan": "Japan",
    "India": "India",
    "Cambodia": "Cambodia",
    "Poland": "Poland",
    "Laos": "Laos",
    "England": "England",
    "Cuba": "Cuba",
    "Taiwan": "Taiwan",
    "Italy": "Italy",
    "Canada": "Canada",
    "Portugal": "Portugal",
    "China": "China",
    "Nicaragua": "Nicaragua",
    "Honduras": "Honduras",
    "Iran": "Iran",
    "Scotland": "Scotland",
    "Jamaica": "Jamaica",
    "Ecuador": "Ecuador",
    "Yugoslavia": "Yugoslavia",
    "Hungary": "Hungary",
    "Hong Kong": "Hong",
    "Greece": "Greece",
    "Trinidad & Tobago": "Trinadad&Tobago",
    "Outlying US (Guam, USVI, etc.)": "Outlying-US(Guam-USVI-etc)",
    "France": "France",
    "Holland / Netherlands": "Holand-Netherlands"
}
